In [1]:
import pandas as pd

report2015 = pd.read_csv('/Users/frodo/Downloads/archive/2015.csv')
report2016 = pd.read_csv('/Users/frodo/Downloads/archive/2016.csv')
report2017 = pd.read_csv('/Users/frodo/Downloads/archive/2017.csv')
report2018 = pd.read_csv('/Users/frodo/Downloads/archive/2018.csv')
report2019 = pd.read_csv('/Users/frodo/Downloads/archive/2019.csv')

# 다섯 개 파일 모두 변수에 할당

print(set(report2015['Country']) - set(report2016['Country']))
print(set(report2016['Country']) - set(report2015['Country']))

region = {}
for i, j in zip(report2015['Country'], report2015['Region']):
    region[i] = j
    
for i, j in zip(report2016['Country'], report2016['Region']):
    region[i] = j
    
region

{'Swaziland', 'Mozambique', 'Somaliland region', 'Oman', 'Lesotho', 'Djibouti', 'Central African Republic'}
{'Belize', 'Puerto Rico', 'Namibia', 'Somalia', 'South Sudan', 'Somaliland Region'}

{'Switzerland': 'Western Europe',
 'Iceland': 'Western Europe',
 'Denmark': 'Western Europe',
 'Norway': 'Western Europe',
 'Canada': 'North America',
 'Finland': 'Western Europe',
 'Netherlands': 'Western Europe',
 'Sweden': 'Western Europe',
 'New Zealand': 'Australia and New Zealand',
 'Australia': 'Australia and New Zealand',
 'Israel': 'Middle East and Northern Africa',
 'Costa Rica': 'Latin America and Caribbean',
 'Austria': 'Western Europe',
 'Mexico': 'Latin America and Caribbean',
 'United States': 'North America',
 'Brazil': 'Latin America and Caribbean',
 'Luxembourg': 'Western Europe',
 'Ireland': 'Western Europe',
 'Belgium': 'Western Europe',
 'United Arab Emirates': 'Middle East and Northern Africa',
 'United Kingdom': 'Western Europe',
 'Oman': 'Middle East and Northern Africa',
 'Venezuela': 'Latin America and Caribbean',
 'Singapore': 'Southeastern Asia',
 'Panama': 'Latin America and Caribbean',
 'Germany': 'Western Europe',
 'Chile': 'Latin America and Caribbean',
 'Qatar': 'Middle East and Northern Africa',
 'France': 'Western Europe',
 'Argentina': 'Latin America and Caribbean',
 'Czech Republic': 'Central and Eastern Europe',
 'Uruguay': 'Latin America and Caribbean',
 'Colombia': 'Latin America and Caribbean',
 'Thailand': 'Southeastern Asia',
 'Saudi Arabia': 'Middle East and Northern Africa',
 'Spain': 'Western Europe',
 'Malta': 'Western Europe',
 'Taiwan': 'Eastern Asia',
 'Kuwait': 'Middle East and Northern Africa',
 'Suriname': 'Latin America and Caribbean',
 'Trinidad and Tobago': 'Latin America and Caribbean',
 'El Salvador': 'Latin America and Caribbean',
 'Guatemala': 'Latin America and Caribbean',
 'Uzbekistan': 'Central and Eastern Europe',
 'Slovakia': 'Central and Eastern Europe',
 'Japan': 'Eastern Asia',
 'South Korea': 'Eastern Asia',
 'Ecuador': 'Latin America and Caribbean',
 'Bahrain': 'Middle East and Northern Africa',
 'Italy': 'Western Europe',
 'Bolivia': 'Latin America and Caribbean',
 'Moldova': 'Central and Eastern Europe',
 'Paraguay': 'Latin America and Caribbean',
 'Kazakhstan': 'Central and Eastern Europe',
 'Slovenia': 'Central and Eastern Europe',
 'Lithuania': 'Central and Eastern Europe',
 'Nicaragua': 'Latin America and Caribbean',
 'Peru': 'Latin America and Caribbean',
 'Belarus': 'Central and Eastern Europe',
 'Poland': 'Central and Eastern Europe',
 'Malaysia': 'Southeastern Asia',
 'Croatia': 'Central and Eastern Europe',
 'Libya': 'Middle East and Northern Africa',
 'Russia': 'Central and Eastern Europe',
 'Jamaica': 'Latin America and Caribbean',
 'North Cyprus': 'Western Europe',
 'Cyprus': 'Western Europe',
 'Algeria': 'Middle East and Northern Africa',
 'Kosovo': 'Central and Eastern Europe',
 'Turkmenistan': 'Central and Eastern Europe',
 'Mauritius': 'Sub-Saharan Africa',
 'Hong Kong': 'Eastern Asia',
 'Estonia': 'Central and Eastern Europe',
 'Indonesia': 'Southeastern Asia',
 'Vietnam': 'Southeastern Asia',
 'Turkey': 'Middle East and Northern Africa',
 'Kyrgyzstan': 'Central and Eastern Europe',
 'Nigeria': 'Sub-Saharan Africa',
 'Bhutan': 'Southern Asia',
 'Azerbaijan': 'Central and Eastern Europe',
 'Pakistan': 'Southern Asia',
 'Jordan': 'Middle East and Northern Africa',
 'Montenegro': 'Central and Eastern Europe',
 'China': 'Eastern Asia',
 'Zambia': 'Sub-Saharan Africa',
 'Romania': 'Central and Eastern Europe',
 'Serbia': 'Central and Eastern Europe',
 'Portugal': 'Western Europe',
 'Latvia': 'Central and Eastern Europe',
 'Philippines': 'Southeastern Asia',
 'Somaliland region': 'Sub-Saharan Africa',
 'Morocco': 'Middle East and Northern Africa',
 'Macedonia': 'Central and Eastern Europe',
 'Mozambique': 'Sub-Saharan Africa',
 'Albania': 'Central and Eastern Europe',
 'Bosnia and Herzegovina': 'Central and Eastern Europe',
 'Lesotho': 'Sub-Saharan Africa',
 'Dominican Republic': 'Latin America and Caribbean',
 'Laos': 'Southeastern Asia',
 'Mongolia': 'Eastern Asia',
 'Swaziland': 'Sub-Saharan Africa',
 'Greece': 'Western Europe',
 'Lebanon': 'Middle East and Northern Africa',
 'Hungary': 'Central and Eastern Europe',
 'Honduras': 'Latin America and Caribbean',
 'Tajikistan': 'Central and Eastern Europe',
 'Tunisia': 'Middle East and Northern Africa',
 'Palestinian Territories': 'Middle East and Northern Africa',
 'Bangladesh': 'Southern Asia',
 'Iran': 'Middle East and Northern Africa',
 'Ukraine': 'Central and Eastern Europe',
 'Iraq': 'Middle East and Northern Africa',
 'South Africa': 'Sub-Saharan Africa',
 'Ghana': 'Sub-Saharan Africa',
 'Zimbabwe': 'Sub-Saharan Africa',
 'Liberia': 'Sub-Saharan Africa',
 'India': 'Southern Asia',
 'Sudan': 'Sub-Saharan Africa',
 'Haiti': 'Latin America and Caribbean',
 'Congo (Kinshasa)': 'Sub-Saharan Africa',
 'Nepal': 'Southern Asia',
 'Ethiopia': 'Sub-Saharan Africa',
 'Sierra Leone': 'Sub-Saharan Africa',
 'Mauritania': 'Sub-Saharan Africa',
 'Kenya': 'Sub-Saharan Africa',
 'Djibouti': 'Sub-Saharan Africa',
 'Armenia': 'Central and Eastern Europe',
 'Botswana': 'Sub-Saharan Africa',
 'Myanmar': 'Southeastern Asia',
 'Georgia': 'Central and Eastern Europe',
 'Malawi': 'Sub-Saharan Africa',
 'Sri Lanka': 'Southern Asia',
 'Cameroon': 'Sub-Saharan Africa',
 'Bulgaria': 'Central and Eastern Europe',
 'Egypt': 'Middle East and Northern Africa',
 'Yemen': 'Middle East and Northern Africa',
 'Angola': 'Sub-Saharan Africa',
 'Mali': 'Sub-Saharan Africa',
 'Congo (Brazzaville)': 'Sub-Saharan Africa',
 'Comoros': 'Sub-Saharan Africa',
 'Uganda': 'Sub-Saharan Africa',
 'Senegal': 'Sub-Saharan Africa',
 'Gabon': 'Sub-Saharan Africa',
 'Niger': 'Sub-Saharan Africa',
 'Cambodia': 'Southeastern Asia',
 'Tanzania': 'Sub-Saharan Africa',
 'Madagascar': 'Sub-Saharan Africa',
 'Central African Republic': 'Sub-Saharan Africa',
 'Chad': 'Sub-Saharan Africa',
 'Guinea': 'Sub-Saharan Africa',
 'Ivory Coast': 'Sub-Saharan Africa',
 'Burkina Faso': 'Sub-Saharan Africa',
 'Afghanistan': 'Southern Asia',
 'Rwanda': 'Sub-Saharan Africa',
 'Benin': 'Sub-Saharan Africa',
 'Syria': 'Middle East and Northern Africa',
 'Burundi': 'Sub-Saharan Africa',
 'Togo': 'Sub-Saharan Africa',
 'Puerto Rico': 'Latin America and Caribbean',
 'Belize': 'Latin America and Caribbean',
 'Somalia': 'Sub-Saharan Africa',
 'Somaliland Region': 'Sub-Saharan Africa',
 'Namibia': 'Sub-Saharan Africa',
 'South Sudan': 'Sub-Saharan Africa'}

In [2]:
report2015.columns = ['Country', 'Region', 'Rank', 'Score', 'Standard Error', 'GDP', 'Social Support',
                      'Healthy Life Expectancy', 'Freedom', 'Corruption', 'Generosity', 'Dystopia Residual']
report2016.columns = ['Country', 'Region', 'Rank', 'Score', 'LCI', 'UCI', 'GDP', 'Social Support',
                      'Healthy Life Expectancy', 'Freedom', 'Corruption', 'Generosity', 'Dystopia Residual']
report2017.columns = ['Country', 'Rank', 'Score', 'UCI', 'LCI', 'GDP', 'Social Support',
                      'Healthy Life Expectancy', 'Freedom', 'Generosity', 'Corruption', 'Dystopia Residual']
report2018.columns = [ 'Rank', 'Country', 'Score', 'GDP', 'Social Support', 'Healthy Life Expectancy',
                      'Freedom', 'Generosity', 'Corruption']
report2019.columns = [ 'Rank', 'Country', 'Score', 'GDP', 'Social Support', 'Healthy Life Expectancy',
                      'Freedom', 'Generosity', 'Corruption']

# 연도 별 파일들의 칼럼 이름을 통일

report2015.drop(['Standard Error', 'Dystopia Residual'], axis = 1, inplace = True)
report2016.drop(['LCI', 'UCI', 'Dystopia Residual'], axis = 1, inplace = True)
report2017.drop(['UCI', 'LCI', 'Dystopia Residual'], axis = 1, inplace = True)

# 사용하지 않을 칼럼들을 삭제

In [3]:
report2017['Region'] = None
report2018['Region'] = None
report2019['Region'] = None

# Region 값을 넣기 위한 칼럼을 추가

report2017 = report2017[['Country', 'Region', 'Rank', 'Score', 'GDP', 'Social Support',
                         'Healthy Life Expectancy', 'Freedom', 'Corruption', 'Generosity']]
report2018 = report2018[['Country', 'Region', 'Rank', 'Score', 'GDP', 'Social Support',
                         'Healthy Life Expectancy', 'Freedom', 'Corruption', 'Generosity']]
report2019 = report2019[['Country', 'Region', 'Rank', 'Score', 'GDP', 'Social Support',
                         'Healthy Life Expectancy', 'Freedom', 'Corruption', 'Generosity']]

# 보고서들의 칼럼 순서를 통일

In [4]:
import warnings

warnings.filterwarnings(action='ignore')

for i in range(len(report2017)):
    if report2017['Country'][i] in region:
        report2017['Region'][i] = region[report2017['Country'][i]]
    else:
        pass

for i in range(len(report2018)):
    if report2018['Country'][i] in region:
        report2018['Region'][i] = region[report2018['Country'][i]]
    else:
        pass

for i in range(len(report2019)):
    if report2019['Country'][i] in region:
        report2019['Region'][i] = region[report2019['Country'][i]]
    else:
        pass

In [5]:
report2017

,Country,Region,Rank,Score,GDP,Social Support,Healthy Life Expectancy,Freedom,Corruption,Generosity
0,Norway,Western Europe,1,7.537,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012
1,Denmark,Western Europe,2,7.522,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280
2,Iceland,Western Europe,3,7.504,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540
3,Switzerland,Western Europe,4,7.494,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549
4,Finland,Western Europe,5,7.469,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483
...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,Sub-Saharan Africa,151,3.471,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756
151,Syria,Middle East and Northern Africa,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664
152,Tanzania,Sub-Saharan Africa,153,3.349,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256
153,Burundi,Sub-Saharan Africa,154,2.905,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435
154,Central African Republic,Sub-Saharan Africa,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876

In [6]:
report2018

,Country,Region,Rank,Score,GDP,Social Support,Healthy Life Expectancy,Freedom,Corruption,Generosity
0,Finland,Western Europe,1,7.632,1.305,1.592,0.874,0.681,0.393,0.202
1,Norway,Western Europe,2,7.594,1.456,1.582,0.861,0.686,0.340,0.286
2,Denmark,Western Europe,3,7.555,1.351,1.590,0.868,0.683,0.408,0.284
3,Iceland,Western Europe,4,7.495,1.343,1.644,0.914,0.677,0.138,0.353
4,Switzerland,Western Europe,5,7.487,1.420,1.549,0.927,0.660,0.357,0.256
...,...,...,...,...,...,...,...,...,...,...
151,Yemen,Middle East and Northern Africa,152,3.355,0.442,1.073,0.343,0.244,0.064,0.083
152,Tanzania,Sub-Saharan Africa,153,3.303,0.455,0.991,0.381,0.481,0.097,0.270
153,South Sudan,Sub-Saharan Africa,154,3.254,0.337,0.608,0.177,0.112,0.106,0.224
154,Central African Republic,Sub-Saharan Africa,155,3.083,0.024,0.000,0.010,0.305,0.038,0.218
155,Burundi,Sub-Saharan Africa,156,2.905,0.091,0.627,0.145,0.065,0.076,0.149

In [7]:
report2019

,Country,Region,Rank,Score,GDP,Social Support,Healthy Life Expectancy,Freedom,Corruption,Generosity
0,Finland,Western Europe,1,7.769,1.340,1.587,0.986,0.596,0.393,0.153
1,Denmark,Western Europe,2,7.600,1.383,1.573,0.996,0.592,0.410,0.252
2,Norway,Western Europe,3,7.554,1.488,1.582,1.028,0.603,0.341,0.271
3,Iceland,Western Europe,4,7.494,1.380,1.624,1.026,0.591,0.118,0.354
4,Netherlands,Western Europe,5,7.488,1.396,1.522,0.999,0.557,0.298,0.322
...,...,...,...,...,...,...,...,...,...,...
151,Rwanda,Sub-Saharan Africa,152,3.334,0.359,0.711,0.614,0.555,0.411,0.217
152,Tanzania,Sub-Saharan Africa,153,3.231,0.476,0.885,0.499,0.417,0.147,0.276
153,Afghanistan,Southern Asia,154,3.203,0.350,0.517,0.361,0.000,0.025,0.158
154,Central African Republic,Sub-Saharan Africa,155,3.083,0.026,0.000,0.105,0.225,0.035,0.235
155,South Sudan,Sub-Saharan Africa,156,2.853,0.306,0.575,0.295,0.010,0.091,0.202